Do not bypass spam detection
pfefferle/wordpress-webmention pull request #443
Opened 2023-12-22 13:18 UTC by pfefferle

In the current code, we bypass spam detection completely, because every Webmentions is always only `1` or `0`.

That makes spam detection useless and with spammers keeping up with new technologies like Webmentions, we should not bother our users to check every Mention.

What do you think @dshanske 

/cc @kbrown9

2023-12-22 15:53 UTC, dshanske requested changes
I'm sort of mixed on this. On one hand, letting WordPress make the decision on this is respecting the system. We have no need to do all moderation inside the plugin. Conversely though, no spam system so far is really equipped to make decisions on webmentions because they don't know what they are. But, the side of not superseding other plugins on the matter seems to win out.

2023-12-22 15:54 UTC, dshanske approved these changes

2023-12-22 16:00 UTC, pfefferle commented
> Conversely though, no spam system so far is really equipped to make decisions on webmentions because they don't know what they are.

That's not completely true, this request came initially from the Akismet team and we are working on supporting Pings in the next version of Antispam Bee!

When we always set all Webmentions either of `1` or `0` Akismet or Antispam Bee have no chance to train their algorithms from false positives for example.

2023-12-22 16:01 UTC, dshanske commented
> > Conversely though, no spam system so far is really equipped to make decisions on webmentions because they don't know what they are.
> 
> That's not completely true, this request came initially from the Akismet team and we are working on supporting Pings in the next version of Antispam Bee!
> 
> When we always set all Webmentions either of `1` or `0` Akismet or Antispam Bee have no chance to train their algorithms from false positives for example.

That's why I approved.

2023-12-22 16:03 UTC, pfefferle commented
Ah, I only saw the red bubble 🫣

But wanted to give you the context anyway!

2023-12-22 16:10 UTC, dshanske commented
> Ah, I only saw the red bubble 🫣
> 
> But wanted to give you the context anyway!

Accidentally clicked the wrong response and fixed it.

2023-12-22 16:26 UTC, merged

2023-12-26 13:16 UTC, cybeardjm commented
Hi @pfefferle - Just updated to the latest version.
Now all pings (reposts, likes...) coming from Bridgy go directly to spam!

2023-12-26 20:39 UTC, pfefferle commented
@cybeardjm have you added "brid.gy" to the allow-list?

@cybeardjm I will talk to the Akismet Team, to see what we can do.

2023-12-26 20:58 UTC, kbrown9 commented
Hi @pfefferle! @cybeardjm did reach out to us, and I'm investigating the issue.

2023-12-26 20:59 UTC, pfefferle commented
Oh even better, thanks @kbrown9

2023-12-26 21:08 UTC, cybeardjm commented
@pfefferle @kbrown9 Nope, didn't modify my allow-list since our last exchange (well, I just removed my own domain, to avoid having some "comments" auto-validated).